name: multicamp_flutter_app_prototype
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  mobx_codegen: ^1.1.2
  http: ^0.12.2
  webview_flutter: ^1.0.7
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  webfeed:
    git: https://github.com/Adem68/webfeed.git
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_launcher_name:
  name: "Haberler"

